server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名

aliyun:
  oss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5tSTEPk2Exaesu2FaMoN
    secret-access-key: wN1oJcKCTCw6yJetNOFMRZxqPH2dUU
    bucket-name: hf-srb-file