server:
  port: 80 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-gateway # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.241.134:8848 # nacos服务地址
    gateway:
      discovery:
        locator:
          enabled: true # 发现 Nacos 中的微服务，并自动生成转发路由
      routes:
      - id: service-core
        uri: lb://service-core
        predicates:
        - Path=/*/core/**
      - id: service-mail
        uri: lb://service-mail
        predicates:
        - Path=/*/mail/**
      - id: service-oss
        uri: lb://service-oss
        predicates:
        - Path=/*/oss/**